### ISSUE TITLE
Question about `load_paths`.

### ISSUE THREAD

**Issue by BToersche** [myFavShrimp/turf#20]
Hi, a question this time.

I am trying to use the `load_paths` option in `Cargo.toml` for some global variables/styling. I've successfully added an SCSS file in the correct folder and this gets picked up by turf.
However, while turf picks up and compiles the stylesheet, it does not seem to do anything useful and does not get added to the file specified at `file_output`.
I can see with `cargo-expand` that the stylesheet does get included in my rust file as follows: `const _ = b"<compiled_stylesheet>";`, but I am not sure what that is supposed to do. Am I missing something here or is this feature unfinished?

Thanks in advance.

Yours,
Bart Toersche

**Comment by myFavShrimp** [comment]
Hey, the stylesheets get included in the Rust file to add them to Cargo's build system dependency tracking so that changes to SCSS files trigger recompilation. If you want to access the resulting CSS you should always use the `ClassName` constants, `class_names`' values or the output files as shown in turf's README.
`load_paths` will only be included in the resulting CSS if they are imported from SCSS files that are fed into turfs macros.

**Comment by BToersche** [comment]
Ah ok, that makes sense.

I've tried to use it for setting variables. So I have a `themes.scss` as a global file which has a bunch of `--color-var-names`. I would like to use those in my local/component stylesheets, which are something like:
```
.my-component {
   color: var(--color-theme-1);
   background-color: var(--background-color-theme-1);
}
```
But because the vars in global are not part of the `my-component` class, they won't get included in the resulting `file_output`.
(Same goes for SCSS-style vars btw, like `$color-theme-1`.)

**Comment by BToersche** [comment]
Thanks for answering. I'll close the ticket.
